### ISSUE TITLE
Async custom validator for API call

### ISSUE THREAD

**Issue by rwwagner90** [nelsonomuto/angular-ui-form-validation#56]
How would one create a custom validator that is passed some data, uses that data to POST to an API and then does different messages based on what the API returns? I don't believe I saw anything about this use case in the documentation. I have created my own custom one for use with a regex, so I'm loosely familiar with how to do it, but do not know how to do this case. I would appreciate any help you can give!

**Comment by geemang2000** [comment]
+1 on this. I'd like to use some serverside validation

**Comment by rwwagner90** [comment]
How goes this? Would like to be able to use this, so we can use the same library for all our validation.

**Comment by NMichas** [comment]
+1 this is definitely a must, we'd love to see it being implemented.

**Comment by rwwagner90** [comment]
@nelsonomuto If you already have a branch to do this, can you please put up some quick docs on how to use it? My application is stalled out until I can finish up this verification. I could do it myself, if you would outline how to manually set the status of the validators and such.

**Comment by rwwagner90** [comment]
@nelsonomuto it's been over a month since we last heard from you. If you have this feature in a branch already, can you just please tell us how to use it? My application cannot continue without this functionality.

**Comment by nelsonomuto** [comment]
i am making good progress under a new branch, this has been a very hard feature to develop. I look to completely test and push it soon. Hopefully tonight, I'm ironing out a few kinks, but so far looks more promising than ever before.

**Comment by nelsonomuto** [comment]
the branch is asynchvalidation

**Comment by rwwagner90** [comment]
I've switched to another validation library, as I needed something that worked now. Thank you for all your help though!

**Comment by nelsonomuto** [comment]
have a look at the asynchvalidation branch, tell me what you think before I merge this into master. The asynchronous validation is inside the dynamic validation object. There is an example in this branch, clone the branch and run grunt serve.

**Comment by rwwagner90** [comment]
Closing this, as I no longer have a need for it.
