### ISSUE TITLE
Dynamically add or remove validations

### ISSUE THREAD

**Issue by krescruz** [nelsonomuto/angular-ui-form-validation#62]
As I can dynamically add or remove the element validations.
Example:

![dina](https://cloud.githubusercontent.com/assets/1160103/6589047/fd6ace70-c75f-11e4-9361-3b0ce713a2d4.png)

if I remove it, it doesn't work, remains validation

**Comment by nelsonomuto** [comment]
http://www.mattzeunert.com/2014/11/03/manually-removing-angular-directives.html

**Comment by nelsonomuto** [comment]
This article explains how to: http://www.mattzeunert.com/2014/11/03/manually-removing-angular-directives.html

I will try and create an API to make it easier

**Comment by nelsonomuto** [comment]
I would advise you use a different approach, instead of manually removing the validation. Just use two inputs and hide the first and show the second one.
