### ISSUE TITLE
Validator needs to pass the scope not the model :S

### ISSUE THREAD

**Issue by danicomas** [nelsonomuto/angular-ui-form-validation#63]
validator: function (errorMessageElement, val, attr, element, model (scope!!!!!!), modelCtrl){
})

@nelsonomuto

**Comment by nelsonomuto** [comment]
The scope is already getting passed as the 7th parameter.

The full signature of the validator element is as follows:
`function (errorMessageElement, val, attr, $element, model, ngModelController, $scope, rawAttr) {
`

**Comment by nelsonomuto** [comment]
I edited the wiki for how to [create your own custom validation](https://github.com/nelsonomuto/angular-ui-form-validation/wiki/Creating-your-own-re-usable-custom-validation-directives) with this information
