### ISSUE TITLE
Version pulled in from bower differs from the posted release.

### ISSUE THREAD

**Issue by Setheck** [nelsonomuto/angular-ui-form-validation#64]
I was looking to test out this plugin, i decided to go the bower route and pull it in, however it crashed my angular app... I discovered that the posted release version ( https://raw.github.com/nelsonomuto/angular-ui-form-validation/master/dist/angular-ui-form-validation.js )
seems to be completely different from the one included with the command
$bower install angular-ui-form-validation

Just to give comparison...
This is the release download
$ md5 angular-ui-form-validation.js 
MD5 (angular-ui-form-validation.js) = ccd8f17363ea94837631c77c323458fd

This is the bower install
$ md5 angular-ui-form-validation.js 
MD5 (angular-ui-form-validation.js) = 4c3cd5d7cc902fe6bde4633aa1a897e5

Any help is appreciated.
Thanks,

**Comment by nelsonomuto** [comment]
That is true, I just confirmed this, for whatever reason, bower is no longer in synch with the github project for angular-ui-form-validation

**Comment by nelsonomuto** [comment]
I will see if I can get this resolved asap

**Comment by daniellecs** [comment]
Nelson, 
Where you able to resolve this? I'm getting a Error: [$injector:unpr] Unknown provider: aProvider <- a <- inputDirective which seems to be related, since all steps were done correctly according to the README and that error comes on page load. Any help would be appreciated!

**Comment by facultymatt** [comment]
Getting the same issue here...

**Comment by nelsonomuto** [comment]
This should now be resolved thanks to @shaunakv1

**Comment by shaunakv1** [comment]
glad to contribute :)

**Comment by almoral** [comment]
I still got this issue on August 12, 2015.
