### ISSUE TITLE
Angular ui-form-validation not working 

### ISSUE THREAD

**Issue by boyfunky** [nelsonomuto/angular-ui-form-validation#68]
I am trying  to use the angular-ui-form validation with basic form but it is not working at all. 

http://plnkr.co/edit/44i7Dp

**Comment by Jainil** [comment]
+1 I am facing the same issue. Seems to be some problem with the minification. Am seeing these errors on the console  `Unknown provider: aProvider <- a <- inputDirective` and `Unknown provider: aProvider <- a <- textareaDirective`

**Comment by Jainil** [comment]
@nelsonomuto This error seems to be on the 2.0.0 release. Please tag the latest 2.0.1 release (which works) so that people using bower can get it. btw: Many thanks for the great work!

**Comment by nelsonomuto** [comment]
ok will do asap

**Comment by nelsonomuto** [comment]
i will send updates on the gitter channel https://gitter.im/nelsonomuto/angular-ui-form-validation

**Comment by nelsonomuto** [comment]
fixed

**Comment by garrylachman** [comment]
still got this issue

**Comment by nelsonomuto** [comment]
fixed in 2.1.3 here is the plunk with the working version http://plnkr.co/edit/DKlgvA?p=preview
