### ISSUE TITLE
Attach custom class to Validation messages  

### ISSUE THREAD

**Issue by NitinPrakash** [nelsonomuto/angular-ui-form-validation#70]
*How can i add Custom class to validation messages ?*

i am using Bootrstrap v3.3.5 for my project and wanted to add class **text-error** for errors and **text-success** for success messages.

I may want to add multiple classes per input depending on validation criteria. But currently i cannot find dosumentation for the same

**Comment by nelsonomuto** [comment]
In the next version I will solve this by adding new attributes,
Use these attributes for live validation success and fail, **validation-live-success-cls, validation-live-fail-cls**

**Comment by nelsonomuto** [comment]
Ex: 
```
    <input type="text" id="username" name="username" ng-model="user.username" validation-min-length="{template:'/views/errorTemplateOne.html', value:5}" validation-no-space="{message:'no space - custom message', value: true}" validation-live-success-cls="text-success" validation-live-fail-cls="text-error">

```
