### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: aProvider <- a <- inputDirective

### ISSUE THREAD

**Issue by garrylachman** [nelsonomuto/angular-ui-form-validation#72]
I use yeoman...
its working when i include the lib but after creating a dist i got this error
Error: [$injector:unpr] Unknown provider: aProvider <- a <- inputDirective

i use 2.1.1...
i try more versions but without success

**Comment by nelsonomuto** [comment]
Not sure what you mean after creating a dist?

**Comment by nelsonomuto** [comment]
fixed in 2.1.3
