### ISSUE TITLE
Select + ngOptions + Validation-Field-Required

### ISSUE THREAD

**Issue by wesleyegberto** [nelsonomuto/angular-ui-form-validation#79]
When the validation-field-required is added to a select which use a ng-options like "obj.label for obj in myArray", the obj isn't set correctly to my model, it always set the obj.label.

Here is the Plunker showing the error: http://plnkr.co/edit/QN62ntl4Uh9PHEsJgY7t?p=preview

Thank you!

**Comment by upendrakolte** [comment]
validation-field-required does not work on Select as mentioned bywesleyegberto
